project_id = "cznvtcvzotilcxajcflw"

[functions.generate-metadata]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false

[functions.download-image]
verify_jwt = false

[functions.cleanup-old-generations]
verify_jwt = false

[functions.image-to-prompt]
verify_jwt = false

[functions.review-file]
verify_jwt = false

[functions.daily-credit-reset]
verify_jwt = false
