project_id = "qwnrymtaokajuqtgdaex"

[functions.send-contact-email]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-user-email]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false
